import { ChesterProduct, LeatherOption } from './types';

export const ATELIER_NAME = "Chester Time";
export const ATELIER_TAGLINE = "İmalatçıdan Doğrudan Chester & Tasarım Koltuk Üretimi";
export const DISPLAY_PHONE = "0536 799 14 40";
export const WHATSAPP_NUMBER = "+905367991440";
export const BUSINESS_ADDRESS = "Kirazlı Mah. 1145 Sok. No: 4/A, Bağcılar / İstanbul, Türkiye";
export const INSTAGRAM_HANDLE = "@chester.time";
export const INSTAGRAM_URL = "https://instagram.com/chester.time";

export function buildWhatsAppUrl(message: string): string {
  const cleanPhone = WHATSAPP_NUMBER.replace(/[^0-9]/g, "");
  return `https://wa.me/${cleanPhone}?text=${encodeURIComponent(message)}`;
}

export const LEATHER_OPTIONS: LeatherOption[] = [
  {
    id: "vintage-taba",
    name: "Antik Taba Silinebilir Deri",
    category: "Vintage Pull-Up",
    origin: "1. Sınıf İthal Silinebilir Döşemelik Deri",
    hex: "#B86B35",
    description: "Zamanla yıpranmayan, nemli bezle kolayca silinen, sıcak taba tonuyla evlere sıcaklık katan popüler Chester derisi.",
    image: "/images/chester/chestertime/product_tan_chester.jpg",
    thickness: "Dayanıklı & Silinebilir Yüzey"
  },
  {
    id: "emerald-velvet",
    name: "Zümrüt Yeşili Lüks Kadife",
    category: "İtalyan Kadife",
    origin: "Su İtici & Leke Tutmaz Dokuma",
    hex: "#1E4D36",
    description: "Işık yansımalarıyla zengin duran, yumuşacık dokulu ve kolay temizlenebilen kadife kumaş.",
    image: "/images/chester/chestertime/product_green_pouf.jpg",
    thickness: "Yüksek Gramajlı Sık Dokuma"
  },
  {
    id: "bordeaux-classic",
    name: "Asil Bordo / Vişne Kumaş & Deri",
    category: "Hakiki İtalyan Derisi",
    origin: "Klasik Chester Renk Serisi",
    hex: "#6B1D28",
    description: "Klasik salon ve çalışma odalarının vazgeçilmezi olan tok ve asil bordo tonu.",
    image: "/images/chester/chestertime/product_red_chester.jpg",
    thickness: "Ağır Gramajlı Döşemelik"
  },
  {
    id: "cream-babyface",
    name: "Krem & Ekru Babyface Kumaş",
    category: "İtalyan Kadife",
    origin: "Yumuşak Tuşeli İpeksi Kumaş",
    hex: "#EFE8DC",
    description: "Geniş ve aydınlık salonlar için ferah, leke tutmaz ve çocuklu ailelere uygun yumuşak doku.",
    image: "/images/chester/chestertime/delivery_cream_chester.jpg",
    thickness: "Silinebilir & Nefes Alan"
  },
  {
    id: "black-charcoal",
    name: "Gece Siyahı Mat Deri",
    category: "Hakiki İtalyan Derisi",
    origin: "Modern & Karizmatik Seri",
    hex: "#1A1918",
    description: "Ofis, çalışma odası veya modern şömineli salonlar için karizmatik mat siyah deri kaplama.",
    image: "/images/chester/chestertime/delivery_black_chester.jpg",
    thickness: "Ekstra Mukavemetli"
  }
];

export const CHESTER_PRODUCTS: ChesterProduct[] = [
  // 1. KANEPE ÇEŞİTLERİ (sofa)
  {
    id: "vintage-english-chester",
    name: "Vintage İngiliz Taba Hakiki Deri Chester",
    category: "sofa",
    tagline: "El yapımı antik eskitme taba deri ve derin kapitone sırt işçiliği.",
    description: "İngiliz malikane tarzından ilham alan klasik Chester formu. Fırınlanmış gürgen iskelet ve el çakımı kabaralarıyla zamansız bir başyapıt.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 235, depth: 100, height: 80 },
    leatherType: "Antik Taba Hakiki / Silinebilir Deri",
    tuftingDepth: "Derin El Kapitonesi & Çelik Çekme Düğmeler",
    cushionFill: "32 DNS HR Sünger + Elyaf Dolgu",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_vintage_english_tan.jpg",
    gallery: ["/images/chester/products/sofa_vintage_english_tan.jpg", "/images/chester/chestertime/product_tan_chester.jpg"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Bordo", "Ekru"],
    sizeOptions: ["210 cm (3'lü)", "235 cm (Geniş 3'lü)", "270 cm (4'lü)", "Özel Salon Ölçüsü"],
    isBestseller: true
  },
  {
    id: "chocolate-vintage-chester-sofa",
    name: "Antik Çikolata Kahve 3'lü Chester Koltuk",
    category: "sofa",
    tagline: "Geleneksel kıvrık kollar, pirinç kabara işçiliği ve kalın yağlı eskitme deri.",
    description: "Orijinal Chesterfield oranlarına sadık kalınarak elde üretilen çikolata kahve 3'lü kanepe, İtalyan kabara çakımı ve usta el kapitonesine sahiptir.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 240, depth: 100, height: 80 },
    leatherType: "Antik Yağlı Çikolata Kahve Deri",
    tuftingDepth: "Derin Usta El Kapitonesi",
    cushionFill: "35 DNS HR Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_chocolate_vintage_chester.jpg",
    gallery: ["/images/chester/products/sofa_chocolate_vintage_chester.jpg"],
    availableLeathers: ["Çikolata Kahve", "Antik Taba", "Bordo", "Gece Siyahı"],
    sizeOptions: ["215 cm", "240 cm Standart", "275 cm Geniş", "Özel Ölçü"],
    isNew: true
  },
  {
    id: "royal-navy-blue-velvet-sofa",
    name: "Gece Mavisi Lüks Kadife Chester Kanepe",
    category: "sofa",
    tagline: "Safir gece mavisi su itici kadife, gümüş nikel ayaklar ve komple kapitone sırt.",
    description: "Gösterişli salonlar ve rezidanslar için safir gece mavisi tonlarında ışıldayan ithal silinebilir kadife döşeme ve derin kapitone düğme işçiliği.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 245, depth: 98, height: 80 },
    leatherType: "İthal Lüks Su İtici Kadife",
    tuftingDepth: "Komple Kapitone Sırt & Kol",
    cushionFill: "32 DNS Soft HR Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_royal_navy_blue_velvet.jpg",
    gallery: ["/images/chester/products/sofa_royal_navy_blue_velvet.jpg"],
    availableLeathers: ["Gece Mavisi", "Zümrüt Yeşili", "Yakut Bordo", "Krem"],
    sizeOptions: ["220 cm", "245 cm Standart", "280 cm Geniş", "Özel Ölçü"],
    isNew: true
  },
  {
    id: "emerald-green-leather-sofa",
    name: "Zümrüt Yeşili Eskitme Deri Chester Kanepe",
    category: "sofa",
    tagline: "Antik mermerli mekanlara özel zümrüt patina deri ve pirinç kabara süslemeleri.",
    description: "Yeşilin en asil tonu olan zümrüt patinalı deri ile kaplanan bu model, pirinç kabaraları ve dik kol formuyla mekanınıza saray zarafeti katar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 210, depth: 95, height: 80 },
    leatherType: "Zümrüt Patina Hakiki / Silinebilir Deri",
    tuftingDepth: "El Kapitonesi Sırt & Kollar",
    cushionFill: "32 DNS Çökmeyen Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_emerald_green_leather.jpg",
    gallery: ["/images/chester/products/sofa_emerald_green_leather.jpg"],
    availableLeathers: ["Zümrüt Yeşili", "Antik Taba", "Bordo", "Siyah"],
    sizeOptions: ["190 cm (2'li)", "210 cm (2.5'luk)", "235 cm (3'lü)"],
    isBestseller: true
  },
  {
    id: "minimalist-loft-camel-sofa",
    name: "Modern Minimalist Camel Deri Blok Kanepe",
    category: "sofa",
    tagline: "Geniş oturum derinliği, deve tüyü sıcak deri dokusu ve loft mimariye özel form.",
    description: "Çağdaş yaşam alanlarına ve minimalist evlere özel tasarlanan camel deri kanepe; dikiş detayları ve kuştüyü yumuşak oturumuyla öne çıkar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 230, depth: 100, height: 75 },
    leatherType: "Camel / Deve Tüyü Yumuşak Dokulu Deri",
    tuftingDepth: "Modern Düz Blok Tasarım",
    cushionFill: "35 DNS HR Sünger + Kaz Tüyü Elyaf",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_minimalist_loft_camel.jpg",
    gallery: ["/images/chester/products/sofa_minimalist_loft_camel.jpg"],
    availableLeathers: ["Camel Taba", "Konyak", "Krem", "Antrasit"],
    sizeOptions: ["210 cm", "230 cm Standart", "260 cm Geniş", "Özel Ölçü"],
    isNew: true
  },
  {
    id: "sage-green-velvet-sofa",
    name: "Adaçayı Yeşili Silinebilir Kadife Chester Kanepe",
    category: "sofa",
    tagline: "Silindir kol destek kırlentleri, konik ahşap ayaklar ve leke tutmaz babyface kadife.",
    description: "Ferah salonlar için dingin adaçayı yeşili tonlarında silinebilir lüks kadife döşeme. Çift minderli geniş oturumu ve sırt konforuyla modern rahatlık.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 235, depth: 95, height: 82 },
    leatherType: "Silinebilir Babyface Kadife",
    tuftingDepth: "Modern Sırt Desteği & Silindir Kırlent",
    cushionFill: "32 DNS Soft Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_sage_green_velvet.jpg",
    gallery: ["/images/chester/products/sofa_sage_green_velvet.jpg"],
    availableLeathers: ["Adaçayı Yeşili", "Ekru Krem", "Vizon Gri", "Pudra"],
    sizeOptions: ["210 cm", "235 cm Standart", "265 cm Geniş", "Özel Ölçü"],
    isNew: true
  },
  {
    id: "studio-camel-tan-sofa",
    name: "Stüdyo Taba Modern Deri Kanepe",
    category: "sofa",
    tagline: "Düz kollar, dikişli sırt minderleri ve ceviz konik ayaklı çağdaş tasarım.",
    description: "Yalın çizgileri ve yumuşak taba deri kaplamasıyla hem ofis hem de oturma odaları için ideal, şık ve ferah bir modern tasarım modeli.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 225, depth: 92, height: 80 },
    leatherType: "Taba Silinebilir Deri",
    tuftingDepth: "Modern Dikişli Sırt Minderleri",
    cushionFill: "32 DNS HR Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_studio_camel_tan.jpg",
    gallery: ["/images/chester/products/sofa_studio_camel_tan.jpg"],
    availableLeathers: ["Taba", "Kahve", "Antrasit", "Krem"],
    sizeOptions: ["200 cm", "225 cm Standart", "250 cm Geniş", "Özel Ölçü"]
  },
  {
    id: "cream-velvet-chester",
    name: "İnci Beyazı & Krem Kadife Chester Kanepe",
    category: "sofa",
    tagline: "Silinebilir leke tutmaz lüks kadife kumaş ve altın detaylı ayak pufu seçeneği.",
    description: "Aydınlık ve ferah yaşam alanları için tasarlanan krem kadife Chester. Yumuşak tuşeli, leke tutmayan kumaşıyla estetik ve konfor bir arada.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 240, depth: 100, height: 78 },
    leatherType: "Silinebilir Lüks İthal Kadife Kumaş",
    tuftingDepth: "Komple El Kapitonesi",
    cushionFill: "32 DNS Soft Konfor Süngeri",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_cream_velvet_chester.jpg",
    gallery: ["/images/chester/products/sofa_cream_velvet_chester.jpg", "/images/chester/chestertime/delivery_cream_chester.jpg"],
    availableLeathers: ["İnci Beyazı", "Ekru Krem", "Vizon", "Açık Gri"],
    sizeOptions: ["210 cm", "240 cm Standart", "270 cm Geniş", "Özel Ölçü"],
    isNew: true
  },
  {
    id: "ruby-bordeaux-chester",
    name: "Asil Yakut Bordo 2'li Chester Koltuk",
    category: "sofa",
    tagline: "Zengin yakut bordo deri dokusu, pirinç kabaralar ve çift kırlent konforu.",
    description: "Prestijli salon ve çalışma odaları için kompakt ve göz alıcı 2'li chester kanepe.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 190, depth: 95, height: 78 },
    leatherType: "1. Sınıf Yakut Bordo Deri",
    tuftingDepth: "Klasik Derin Kapitone",
    cushionFill: "32 DNS Çökmeyen Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_ruby_bordeaux_chester.jpg",
    gallery: ["/images/chester/products/sofa_ruby_bordeaux_chester.jpg", "/images/chester/chestertime/real_deliveries/delivery_9_bordeaux_classic.webp"],
    availableLeathers: ["Yakut Bordo", "Klasik Bordo", "Taba", "Siyah"],
    sizeOptions: ["170 cm (Kompakt 2'li)", "190 cm (Geniş 2'li)", "220 cm (3'lü)"]
  },
  {
    id: "modern-loft-tan",
    name: "Modern Loft Taba Deri Tasarım Koltuk",
    category: "sofa",
    tagline: "Minimalist düz kol çizgileri, masif konik ahşap ayaklar ve yumuşak oturum.",
    description: "Modern ve İskandinav esintileri taşıyan çağdaş deri kanepe. Geniş minder yapısıyla yüksek konfor sunar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 225, depth: 92, height: 82 },
    leatherType: "Vintage Taba Döşemelik Deri",
    tuftingDepth: "Modern Düz Hatlar & Çift Sıra Dikiş",
    cushionFill: "32 DNS HR Sünger + Kaz Tüyü Hissiyatlı Elyaf",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_modern_loft_tan.jpg",
    gallery: ["/images/chester/products/sofa_modern_loft_tan.jpg", "/images/chester/chestertime/product_dyna_kanepe.jpg"],
    availableLeathers: ["Antik Taba", "Konyak Kahve", "Antrasit", "Taba Nubuk"],
    sizeOptions: ["200 cm (3'lü)", "225 cm (Geniş 3'lü)", "250 cm (4'lü)", "Özel Ölçü"]
  },
  {
    id: "anthracite-black-chester",
    name: "Mat Siyah & Antrasit Hakiki Deri Chester",
    category: "sofa",
    tagline: "Karizmatik mat siyah deri dokusu, pirinç kabaralı kol detayları ve masif ahşap ayaklar.",
    description: "Modern salon, rezidans ve ofisler için ağırbaşlı ve karizmatik mat siyah chester kanepe.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 235, depth: 100, height: 78 },
    leatherType: "1. Kalite Mat Siyah Silinebilir Deri",
    tuftingDepth: "Derin El Kapitonesi",
    cushionFill: "32 DNS Sünger Katmanı",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/sofa_anthracite_black_chester.jpg",
    gallery: ["/images/chester/products/sofa_anthracite_black_chester.jpg", "/images/chester/chestertime/delivery_black_chester.jpg"],
    availableLeathers: ["Mat Siyah", "Antrasit", "Koyu Kahve", "Taba"],
    sizeOptions: ["210 cm", "235 cm Standart", "265 cm Geniş", "Özel Ölçü"]
  },
  {
    id: "dyna-kanepe",
    name: "Dyna Kanepe (Tasarım Koltuk)",
    category: "sofa",
    tagline: "Şık, kaliteli ve unutulmaz. Modern düz kol tasarımı ve masif ahşap ayaklar.",
    description: "Chester Time özel tasarım serisinin en çok satan modeli. Hem modern hem sıcak havasıyla salonunuzun havasını değiştirir.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 230, depth: 95, height: 80 },
    leatherType: "Antik Taba Deri / Silinebilir Kumaş",
    tuftingDepth: "Düz Modern Hatlar & Masif Ayak",
    cushionFill: "32 DNS HR Sünger + Elyaf Dolgu",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/product_dyna_kanepe.jpg",
    gallery: ["/images/chester/chestertime/product_dyna_kanepe.jpg", "/images/chester/chestertime/delivery_camel_straight.jpg"],
    availableLeathers: ["Antik Taba Deri", "Krem Kumaş", "Koyu Yeşil", "Antrasit"],
    sizeOptions: ["210 cm (3'lü)", "230 cm (Geniş 3'lü)", "260 cm (4'lü)", "Özel Ölçü"]
  },
  {
    id: "lord-tan-chester",
    name: "Klasik Taba 3'lü Chester Koltuk",
    category: "sofa",
    tagline: "Derin el kapitonesi, fırınlanmış gürgen iskelet ve el çakımı kabaralar.",
    description: "Zamanın eskitemediği klasik Chesterfield formu. Bağcılar atölyemizde usta eller tarafından tek tek düğümlenir.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 235, depth: 100, height: 78 },
    leatherType: "1. Kalite Taba Silinebilir Deri",
    tuftingDepth: "Derin El Kapitonesi & Çelik Çekme Düğmeler",
    cushionFill: "32 DNS Çökmeyen Sünger Katmanı",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/product_tan_chester.jpg",
    gallery: ["/images/chester/chestertime/product_tan_chester.jpg", "/images/chester/chestertime/delivery_tan_ottoman.jpg"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Bordo", "Ekru Krem"],
    sizeOptions: ["210 cm", "235 cm Standart", "270 cm Geniş", "Özel Salon Ölçüsü"]
  },

  // 2. BERJER VE PUF ÇEŞİTLERİ (armchair)
  {
    id: "library-tan-puf-armchair",
    name: "Kütüphane Taba Chester Berjer & Ayak Pufu Seti",
    category: "armchair",
    tagline: "Özel ayak uzatma pufu, antik taba eskitme deri ve pirinç döküm teker detayları.",
    description: "Çalışma odaları, kütüphaneler ve şömine başı için nostaljik taba rengi hakiki deri kaplama, ortopedik sırt desteği ve eşlik eden kapitone pufuyla tam bir dinlenme konforu sunar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 95, depth: 92, height: 100 },
    leatherType: "Antik Taba Hakiki / Eskitme Deri",
    tuftingDepth: "Derin El Kapitonesi Sırt & Puf",
    cushionFill: "35 DNS Ortopedik HR Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/armchair_library_tan_puf.jpg",
    gallery: ["/images/chester/products/armchair_library_tan_puf.jpg"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Konyak", "Bordo"],
    sizeOptions: ["Tekli Berjer", "Berjer + Ayak Pufu Takımı"],
    isBestseller: true
  },
  {
    id: "cigar-brown-club-armchair",
    name: "Puro Kahve Vintage Deri Club Berjer",
    category: "armchair",
    tagline: "Geniş kavisli kolçaklar, derin el kapitonesi ve eskitme puro kahve deri dokusu.",
    description: "Klasik İngiliz kulüp ve şömine başı ambiyansını evinize taşıyan puro kahve tonlarında tok hakiki deri berjer, fırınlanmış gürgen iskeletiyle ömürlük kullanım sağlar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 98, depth: 95, height: 82 },
    leatherType: "Vintage Yağlı Puro Kahve Deri",
    tuftingDepth: "Usta İşi Derin Kapitone",
    cushionFill: "32 DNS Yoğun Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/armchair_cigar_brown_club.jpg",
    gallery: ["/images/chester/products/armchair_cigar_brown_club.jpg"],
    availableLeathers: ["Puro Kahve", "Antik Taba", "Koyu Bordo", "Mat Siyah"],
    sizeOptions: ["Tekli Berjer", "İkili Berjer Takımı"],
    isNew: true
  },
  {
    id: "mustard-yellow-velvet-armchair",
    name: "Hardal Sarısı Kadife Chester Berjer",
    category: "armchair",
    tagline: "Altın yüzüklü ahşap ayaklar, pirinç kabara detayları ve sıcak hardal kadife.",
    description: "Mekanlara neşeli ve enerjik bir lüks dokunuş katan hardal sarısı silinebilir kadife berjer, derin sırt kapitonesi ve ergonomik oturumuyla göz kamaştırır.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 92, depth: 88, height: 86 },
    leatherType: "Silinebilir Lüks Hardal Kadife",
    tuftingDepth: "El Kapitonesi & Pirinç Kabaralar",
    cushionFill: "32 DNS Soft Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/armchair_mustard_yellow_velvet.jpg",
    gallery: ["/images/chester/products/armchair_mustard_yellow_velvet.jpg"],
    availableLeathers: ["Hardal Sarısı", "Zümrüt Yeşili", "Mürdüm Moru", "Krem"],
    sizeOptions: ["Tekli Berjer", "Berjer + Puf Takımı"],
    isNew: true
  },
  {
    id: "fireplace-tan-armchair",
    name: "Şömine Başı Klasik Taba Chester Berjer",
    category: "armchair",
    tagline: "Sıcak taba rengi, derin kapitone sırt formu ve rahat okuma koltuğu ergonomisi.",
    description: "Şömine karşısı, çalışma odası veya salon köşesi için el işçiliğiyle üretilmiş nostaljik ve lüks tekli Chester berjer.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 95, depth: 90, height: 82 },
    leatherType: "Antik Taba Silinebilir Hakiki Deri Dokulu",
    tuftingDepth: "Derin El Kapitonesi Sırt & Kollar",
    cushionFill: "32 DNS Yumuşak Oturum Süngeri",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/armchair_fireplace_tan_chester.jpg",
    gallery: ["/images/chester/products/armchair_fireplace_tan_chester.jpg", "/images/chester/chestertime/product_berjer_puf.jpg"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Bordo", "Siyah"],
    sizeOptions: ["Tekli Berjer", "İkili Berjer Seti", "Berjer + Puf Takımı"],
    isBestseller: true
  },
  {
    id: "purple-velvet-armchair",
    name: "Mürdüm Moru Kadife Chester Berjer",
    category: "armchair",
    tagline: "Altın yüzüklü ahşap ayaklar, silinebilir mürdüm kadife ve özel kabara işçiliği.",
    description: "Göz alıcı mürdüm kadife kumaş, altın ayak detayları ve derin kapitone sırt yapısıyla mekanınıza zarafet katar.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 90, depth: 88, height: 86 },
    leatherType: "Silinebilir İtalyan Kadife Kumaş",
    tuftingDepth: "El Kapitonesi Sırt & Kabara Detay",
    cushionFill: "32 DNS Soft Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/armchair_purple_velvet_chester.jpg",
    gallery: ["/images/chester/products/armchair_purple_velvet_chester.jpg", "/images/chester/chestertime/product_purple_berjer.jpg"],
    availableLeathers: ["Mürdüm Moru", "Zümrüt Yeşili", "Gece Mavisi", "Hardal Sarısı"],
    sizeOptions: ["Tekli Berjer", "Berjer + Puf Takımı"],
    isNew: true
  },
  {
    id: "chester-berjer-puf-set",
    name: "Chester Berjer & Ayak Pufu Seti",
    category: "armchair",
    tagline: "Yüksek sırtlı ergonomik okuma berjeri ve uyumlu kapitone ayak pufu.",
    description: "Şömine önü, TV karşısı veya salon köşesi için hem dinlendirici hem çok şık berjer ve puf takımı. Masif torna ayaklı.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 85, depth: 90, height: 105 },
    leatherType: "Antik Taba Deri / Nubuk",
    tuftingDepth: "Sırt Kapitone Düğmeleme",
    cushionFill: "Soft Oturum Süngeri",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/product_berjer_puf.jpg",
    gallery: ["/images/chester/chestertime/product_berjer_puf.jpg", "/images/chester/chestertime/product_purple_berjer.jpg"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Zümrüt Yeşili", "Mürdüm Moru"],
    sizeOptions: ["Tek Berjer", "Berjer + Ayak Pufu Takımı"]
  },
  {
    id: "green-round-pouf-daybed",
    name: "Zümrüt Yeşili Yuvarlak Kapitone Puf",
    category: "armchair",
    tagline: "Geniş yuvarlak formuyla hem orta sehpa hem ekstra oturum ve dinlenme alanı.",
    description: "Tüm çevresi ve üstü el kapitonesiyle döşenmiş, torna masif ayaklı, çok amaçlı lüks salon pufu.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 100, depth: 100, height: 45 },
    leatherType: "Zümrüt Yeşili İtalyan Kadife",
    tuftingDepth: "Komple El Kapitonesi",
    cushionFill: "32 DNS Yoğun Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/product_green_pouf.jpg",
    gallery: ["/images/chester/chestertime/product_green_pouf.jpg"],
    availableLeathers: ["Zümrüt Yeşili", "Taba Deri", "Bordo", "Krem"],
    sizeOptions: ["Ø 90 cm", "Ø 110 cm", "Özel Çap"]
  },
  {
    id: "tan-chester-pouf-combo",
    name: "Taba Chester & Kapitone Puf Takımı",
    category: "armchair",
    tagline: "Koltukla birebir uyumlu el işçiliği yuvarlak kapitone puf kombini.",
    description: "Uyumlu deri dokusu ve özel dikişleriyle takım olarak sunulan berjer ve puf çözümü.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 95, depth: 95, height: 45 },
    leatherType: "1. Kalite Taba Silinebilir Deri",
    tuftingDepth: "El Kapitonesi",
    cushionFill: "32 DNS Soft Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/real_deliveries/delivery_3_tan_puf.webp",
    gallery: ["/images/chester/chestertime/real_deliveries/delivery_3_tan_puf.webp"],
    availableLeathers: ["Antik Taba", "Konyak Deri", "Kahve"],
    sizeOptions: ["Puf Tekli", "Puf + Koltuk Seti"]
  },

  // 3. OTURMA TAKIMLARI (set)
  {
    id: "chester-salon-takimi-3211",
    name: "Taba Deri 3+2+1+1 Komple Salon Takımı",
    category: "set",
    tagline: "3'lü kanepe, 2'li koltuk ve 2 adet tekli berjerden oluşan eksiksiz salon takımı.",
    description: "Tüm salonunuzu tek seferde tamamlayan, fırınlanmış gürgen karkaslı ve 10 yıl garantili komple takım.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 235, depth: 100, height: 78 },
    leatherType: "1. Kalite Taba Silinebilir Deri",
    tuftingDepth: "Komple El Kapitonesi",
    cushionFill: "32 DNS HR Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/real_deliveries/delivery_5_tan_salon_set.webp",
    gallery: ["/images/chester/chestertime/real_deliveries/delivery_5_tan_salon_set.webp"],
    availableLeathers: ["Antik Taba", "Puro Kahve", "Ekru Krem", "Antrasit"],
    sizeOptions: ["3+2+1+1 Komple Takım", "3+3+1 Takım", "3+1+1 Takım", "Özel Kombinasyon"],
    isBestseller: true
  },
  {
    id: "executive-office-set",
    name: "Lüks Yönetici Ofisi & Makam Koltuk Takımı",
    category: "set",
    tagline: "Makam odaları ve prestijli ofisler için 3'lü koltuk ve ikili tekli berjer takımı.",
    description: "Ağırbaşlı ve prestijli tasarımıyla yönetici odalarına şıklık katan hakiki ve silinebilir deri seçenekli takım.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 230, depth: 95, height: 80 },
    leatherType: "Ağır Hizmet Silinebilir Deri",
    tuftingDepth: "Derin El Kapitonesi",
    cushionFill: "35 DNS Yüksek Yoğunluklu Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/real_deliveries/delivery_4_executive_office.webp",
    gallery: ["/images/chester/chestertime/real_deliveries/delivery_4_executive_office.webp"],
    availableLeathers: ["Taba", "Kahve", "Siyah", "Bordo"],
    sizeOptions: ["3+1+1 Makam Takımı", "3+2+1 Takım", "Özel Ofis Ölçüsü"]
  },
  {
    id: "office-cafe-project",
    name: "Cafe, Restoran & VIP Loca Projeleri",
    category: "set",
    tagline: "Toplu ve ticari mekanlar için yüksek dayanımlı imalat fiyatlı Chester üretimi.",
    description: "Kafe, restoran, otel lobisi ve yönetici ofisleri için adetli üretim ve mekan projelendirme desteği.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 200, depth: 90, height: 78 },
    leatherType: "Ağır Hizmet Silinebilir Deri",
    tuftingDepth: "Yoğun Kullanıma Uygun Güçlendirilmiş Düğüm",
    cushionFill: "35 DNS Yüksek Yoğunluklu Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/delivery_office_project.jpg",
    gallery: ["/images/chester/chestertime/delivery_office_project.jpg"],
    availableLeathers: ["Taba", "Kahve", "Siyah", "Bordo", "Yeşil"],
    sizeOptions: ["Adetli Özel İmalat", "Sedir Tipi Chester", "Loca Koltukları"]
  },

  // 4. KÖŞE L KOLTUK TAKIMLARI (corner)
  {
    id: "manor-bordeaux-corner-sofa",
    name: "Kraliyet Bordo Deri Chester Köşe Takımı",
    category: "corner",
    tagline: "İngiliz malikane tarzı komple kapitone sırt ve masif ceviz torna ayaklar.",
    description: "Geniş salonlar ve prestijli mekanlar için tasarlanan L köşe modeli, eskitme antik bordo hakiki deri dokusu, derin düğme kapitonesi ve 35 DNS HR sünger konforuyla üretilmektedir.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 320, depth: 240, height: 82 },
    leatherType: "Antik Eskitme Bordo Hakiki / Silinebilir Deri",
    tuftingDepth: "Komple El Kapitonesi Sırt & Kollar",
    cushionFill: "35 DNS HR Sünger + Kaz Tüyü Elyaf",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/corner_manor_bordeaux_leather.jpg",
    gallery: ["/images/chester/products/corner_manor_bordeaux_leather.jpg"],
    availableLeathers: ["Kraliyet Bordo", "Antik Taba", "Zümrüt Yeşili", "Gece Siyahı"],
    sizeOptions: ["280 × 200 cm", "320 × 240 cm Standart", "360 × 280 cm", "Özel Salon Ölçüsü"],
    isBestseller: true
  },
  {
    id: "mansion-bordeaux-corner",
    name: "Antik Bordo Deri Chester Köşe Takımı",
    category: "corner",
    tagline: "Geniş salonlar için mekana özel ölçülü, derin el kapitonesi ve masif torna ayaklar.",
    description: "Asil bordo derisi, geniş oturum derinliği ve zengin kapitone işçiliğiyle salonunuzun prestij simgesi olacak lüks L köşe.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 320, depth: 250, height: 80 },
    leatherType: "Antik Eskitme Bordo Silinebilir Deri",
    tuftingDepth: "Komple El Kapitonesi Sırt & Kollar",
    cushionFill: "32 DNS HR Sünger + Elyaf Katmanı",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/products/corner_bordeaux_mansion_chester.jpg",
    gallery: ["/images/chester/products/corner_bordeaux_mansion_chester.jpg", "/images/chester/chestertime/real_deliveries/delivery_9_bordeaux_classic.webp"],
    availableLeathers: ["Antik Bordo", "Taba", "Zümrüt Yeşili", "Gece Siyahı"],
    sizeOptions: ["280 × 200 cm", "320 × 250 cm", "360 × 280 cm", "Özel Mekan Ölçüsü"],
    isNew: true
  },
  {
    id: "emerald-chester-corner",
    name: "Zümrüt Yeşili Deri Chester L Köşe",
    category: "corner",
    tagline: "Mekana özel ölçülendirilmiş lüks zümrüt yeşili kapitone köşe takımı.",
    description: "Salonların odak noktası olan, yumuşak dokulu ve dayanıklı zümrüt yeşili özel üretim köşe modeli.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 310, depth: 230, height: 78 },
    leatherType: "Zümrüt Yeşili Deri / Kadife",
    tuftingDepth: "Derin El Kapitonesi",
    cushionFill: "32 DNS Soft Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/real_deliveries/delivery_6_emerald_corner.webp",
    gallery: ["/images/chester/chestertime/real_deliveries/delivery_6_emerald_corner.webp"],
    availableLeathers: ["Zümrüt Yeşili", "Taba", "Siyah", "Bordo"],
    sizeOptions: ["290 × 210 cm", "310 × 230 cm", "Özel Ölçü"]
  },
  {
    id: "mustard-chester-corner",
    name: "Hardal Sarısı Kadife Chester Köşe",
    category: "corner",
    tagline: "Canlı hardal tonu, leke tutmaz kadife dokusu ve konforlu geniş oturumuyla.",
    description: "Sıcak ve modern bir yaşam alanı arayanlar için silinebilir kadife kumaşlı özel tasarım köşe.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 300, depth: 220, height: 78 },
    leatherType: "Silinebilir Hardal Kadife Kumaş",
    tuftingDepth: "Komple Kapitone Düğmeleme",
    cushionFill: "32 DNS Sünger",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/real_deliveries/delivery_8_mustard_corner.webp",
    gallery: ["/images/chester/chestertime/real_deliveries/delivery_8_mustard_corner.webp"],
    availableLeathers: ["Hardal Sarısı", "Krem", "Vizon", "Gri"],
    sizeOptions: ["280 × 200 cm", "300 × 220 cm", "Özel Ölçü"]
  },
  {
    id: "chester-corner-suite",
    name: "Chester Time Taba Deri Köşe Takımı",
    category: "corner",
    tagline: "Geniş aileler ve salonlar için kesintisiz kapitone sırtlı L koltuk konforu.",
    description: "Odanızın köşe yönüne ve ölçülerine göre sıfırdan üretilir. İster sağ ister sol köşe olarak sipariş verebilirsiniz.",
    startingPrice: "Fiyat Al",
    dimensions: { length: 320, depth: 240, height: 78 },
    leatherType: "İstenen Renkte Deri veya Kumaş",
    tuftingDepth: "Komple Kapitone Sırt & Kol",
    cushionFill: "32 DNS Rahat Oturum Süngeri",
    warranty: "10 Yıl Masif İskelet Garantisi",
    primaryImage: "/images/chester/chestertime/product_cognac_chester.jpg",
    gallery: ["/images/chester/chestertime/product_cognac_chester.jpg"],
    availableLeathers: ["Antik Taba", "Krem", "Yeşil", "Antrasit"],
    sizeOptions: ["280 × 200 cm", "320 × 240 cm", "360 × 280 cm", "Özel Oda Ölçüsü"]
  }
];
